### ISSUE TITLE
Minecraft 1.18.2 Bar in the middle of screen - Barra en medio

### ISSUE THREAD

**Issue by Reisanji** [AldairNT74/HygieneMod#1]
![2022-04-14_20 31 25](https://user-images.githubusercontent.com/53265963/163503967-be246de5-29d8-42bd-b888-120b14e3c2fd.png)

Hygiene bar in middle of screen.
ALT - up does nothing, ALT - down moves it a little then makes it dissapear.

Barra de higiene en medio de la pantalla.
ALT - arriba no hace nada, ALT - abajo lo mueve un poco y luego lo hace desaparecer.

**Comment by Reisanji** [comment]
![2022-04-17_16 08 52](https://user-images.githubusercontent.com/53265963/163732147-382aa65f-9633-4776-b91a-8e6d8d211c77.png)
.
Looks like it's fixed.

Parece que está arreglado.

**Comment by AldairNT74** [comment]
I'm sorry for not reading you, I already fixed it.Thank you very much for reporting the bug.

**Comment by Reisanji** [comment]
No problema, de nada.
