### ISSUE TITLE
Right-clicking a cornflower with a bottle crashes the game

### ISSUE THREAD

**Issue by cutecatalina** [AldairNT74/HygieneMod#2]
When I right-clicked on a cornflower with a bottle of water, the game crashed. I am using Forge 1.16.5 and its version is forge-1.16.5-36.2.20 *recommended version* and I will use the latest recommended version that came out 17 days ago which is 1.16.5 - 36.2.34

" Cuando hice clic con el botón derecho en un aciano con una botella de agua, el juego se bloqueó. Estoy usando Forge 1.16.5 y su versión es forge-1.16.5-36.2.20 *versión recomendada* y usaré la última versión recomendada que salió hace 17 días que es 1.16.5 - 36.2.34 "

**Comment by AldairNT74** [comment]
The problem must be another mod that is blocking it, you can go to the game's crash reports folder and send me the text you have with the recent date of the crash.
